Donovan Griego
9-24-2020
Lab 3

Script started on 2020-09-24 20:12:23-06:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="80" LINES="24"]
]0;dxgriego@Parallels: ~/cse113/lab3[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab3[00m$ exit./creditgcc -g -Wall credit.c -o creditexit[Kgcc -g -Wall credit.c -o credit
]0;dxgriego@Parallels: ~/cse113/lab3[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab3[00m$ gcc -g -Wall credit.c -o creditexit[K./credit
Please enter a credit card number to check: 4012888888881881
The card 4012888888881881 is Valid
]0;dxgriego@Parallels: ~/cse113/lab3[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab3[00m$ ./creditgcc -g -Wall credit.c -o credit./credit[K
Please enter a credit card number to check: 4012888888881882
The card 4012888888881882 is Invalid
]0;dxgriego@Parallels: ~/cse113/lab3[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab3[00m$ ./creditgcc -g -Wall credit.c -o creditexit[K
exit

Script done on 2020-09-24 20:12:56-06:00 [COMMAND_EXIT_CODE="0"]
